import { StyleSheet } from "react-native";
import { normalize } from "../../utils/dimensions";

export const styles = StyleSheet.create({

  editIcon: {
    position: "absolute",
    bottom: 10,
    right: 10,
    backgroundColor: "white",
    borderRadius: 15,
    padding: 4,
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },  
  container: {
    flex: 1,
    paddingTop: normalize(10), // Menos espacio arriba para subir el formulario
  },
  header: {
    backgroundColor: "#6B7F7D",
    padding: 15,
    alignItems: "center",
  },
  headerText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  profileContainer: {
    alignItems: "center",
    marginTop: 30,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: "#fff",  // Borde blanco
    shadowColor: "#000", 
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  editButton: {
    marginTop: 10,
    backgroundColor: "#A9A9A9",  // Gris
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 25,
    shadowColor: "#000", 
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 3,
  },
  editButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },
  form: {
    marginTop: 0,
    paddingTop: 30,
    paddingHorizontal: 25,
    paddingBottom: 35, // Menos espacio abajo
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    marginTop: 20,
    color: "#fff",  // Las letras de las etiquetas son blancas
  },
  input: {
    backgroundColor: "rgba(169, 169, 169, 0.5)",  // Gris con opacidad
    paddingVertical: 14,
    paddingHorizontal: 15,
    borderRadius: 10,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#ddd",
    fontSize: 16,
    color: "#fff",  // Las letras dentro del input son blancas
    shadowColor: "#000", 
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 2,
  },
  button: {
    backgroundColor: "#137C6B",
    paddingVertical: 14,
    borderRadius: 10,
    marginTop: 30,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 4,
    marginBottom: 30, // Menos espacio abajo del botón
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  footer: {
    backgroundColor: "#005550",
    padding: 10,
    alignItems: "center",
    position: "absolute",
    bottom: 0,
    width: "100%",
  },
  footerText: {
    color: "#fff",
  },
  footerLink: {
    color: "#FFB400",
    fontWeight: "bold",
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    position: 'absolute',
    right: 10, 
  },
  backArrowContainer: {
    position: 'absolute',
    top: normalize(20), 
    left: 10,  
    zIndex: 1, 
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  phoneLoadingContainer: {
    padding: 20,
    alignItems: 'center',
  },
  phoneLoadingText: {
    color: '#fff',
    marginTop: 8,
    fontSize: 14,
  },
  modalSaveButton: {
    flex: 1,
    marginLeft: 10,
    borderRadius: 8,
    overflow: 'hidden',
  },
  modalSaveButtonGradient: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSaveButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalSaveButtonDisabled: {
    opacity: 0.6,
  },
  modalCancelButton: {
    flex: 1,
    marginRight: 10,
    borderRadius: 8,
    backgroundColor: '#f0f0f0',
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancelButtonText: {
    color: '#666',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalButtons: {
    flexDirection: 'row',
    marginTop: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    width: '90%',
    maxWidth: 400,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  modalContent: {
    width: '100%',
  },
  errorText: {
    color: '#ff4444',
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    width: '100%',
    paddingHorizontal: 20,
  },
  profileIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  profileTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    flex: 1,
  },
  formContainer: {
    width: '100%',
    paddingHorizontal: 20,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 12,
    marginBottom: 15,
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  inputIcon: {
    marginRight: 10,
  },
  inputNew: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
  inputDisabled: {
    opacity: 0.6,
  },
  passwordToggle: {
    padding: 5,
  },
  saveButton: {
    marginTop: 20,
    borderRadius: 12,
    overflow: 'hidden',
  },
  saveButtonGradient: {
    paddingVertical: 15,
    paddingHorizontal: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  phoneSection: {
    width: '100%',
    paddingHorizontal: 20,
    marginTop: 20,
  },
  phoneSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  addPhoneButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  phoneItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 15,
    marginBottom: 10,
  },
  phoneItemContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  phoneItemText: {
    marginLeft: 10,
    flex: 1,
  },
  phoneNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  phoneDetail: {
    fontSize: 14,
    color: '#666',
    marginTop: 2,
  },
  emptyPhoneContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyPhoneText: {
    color: '#fff',
    fontSize: 16,
    marginTop: 10,
  },
  emptyPhoneSubtext: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 14,
    marginTop: 5,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 20,
  },
 
  profileAvatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#e0f2f1',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  profileAvatarText: {
    fontSize: 44,
    color: '#137C6B',
    fontWeight: 'bold',
  },
  editButtonStyled: {
    backgroundColor: '#137C6B',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  phoneSectionContainer: {
    marginTop: 18,
  },
  phoneSectionTitleText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
    marginBottom: 6,
  },
  phoneLoadingView: {
    padding: 20,
    alignItems: 'center',
  },
  phoneLoadingMessage: {
    color: '#fff',
    marginTop: 8,
  },
  phoneItemContainer: {
    backgroundColor: '#e0f2f1',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginBottom: 8,
    minHeight: 52,
    justifyContent: 'center',
    width: '100%',
    alignSelf: 'center',
    maxWidth: 400,
  },
  phoneItemTitleText: {
    color: '#137C6B',
    fontWeight: 'bold',
    fontSize: 15,
    marginBottom: 2,
  },
  phoneItemNumberText: {
    color: '#222',
    fontSize: 15,
  },
  noPhoneContainer: {
    padding: 20,
    alignItems: 'center',
  },
  noPhoneText: {
    color: '#fff',
    fontSize: 14,
    opacity: 0.7,
  },
  passwordPlaceholder: {
    color: '#fff',
  },
  saveButtonEdit: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: '50%',
    minWidth: 180,
    maxWidth: 340,
  },
  saveButtonEditDisabled: {
    opacity: 0.6,
  },
  addPhoneSection: {
    alignItems: 'center',
    marginBottom: 24,
    marginTop: 10,
    width: '100%',
  },
  addPhonePrompt: {
    color: '#fff',
    fontSize: 15,
    marginBottom: 8,
  },
  addPhoneBtn: {
    backgroundColor: '#1db954',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 3,
    marginTop: 2,
    alignSelf: 'center',
    minWidth: 180,
    maxWidth: 340,
  },
  addPhoneBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalKeyboardAvoidingView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  modalContentContainer: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 28,
    width: 320,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
  },
  modalTitleText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#137C6B',
    marginBottom: 12,
  },
  modalInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    borderRadius: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
    width: '100%',
  },
  modalInputIcon: {
    marginRight: 8,
  },
  modalInput: {
    flex: 1,
    fontSize: 16,
    color: '#222',
    paddingVertical: 10,
  },
  modalInputPlaceholder: {
    color: '#aaa',
  },
  modalSaveBtn: {
    backgroundColor: '#137C6B',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 28,
    borderRadius: 20,
    marginTop: 6,
  },
  modalSaveBtnIcon: {
    marginRight: 6,
  },
  modalSaveBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalCancelBtn: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalCancelBtnIcon: {
    marginRight: 6,
  },
  modalCancelBtnText: {
    color: '#137C6B',
    fontWeight: 'bold',
    fontSize: 16,
  },
});
