import { useState, useCallback, useEffect } from 'react';
import { Contact } from '../../domain/entities/Contact';
import { container } from '../../infrastructure/di/container';
import { Alert } from 'react-native';

export const useContactsViewModel = () => {
    const [contacts, setContacts] = useState<Contact[]>([]);
    const [requests, setRequests] = useState<any[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    const fetchContacts = useCallback(async () => {
        try {
            setIsLoading(true);
            const user = await container.getCurrentUserUseCase.execute();
            if (!user) return;

            const [fetchedContacts, fetchedRequests] = await Promise.all([
                container.getContactsUseCase.execute(String(user.id)),
                container.getPendingRequestsUseCase.execute(String(user.id))
            ]);

            setContacts(fetchedContacts);
            setRequests(fetchedRequests);

        } catch (err: any) {
            console.error('Error fetching contacts:', err);
            setError('No se pudieron cargar los contactos');
        } finally {
            setIsLoading(false);
        }
    }, []);

    useEffect(() => {
        fetchContacts();
    }, [fetchContacts]);

    const respondToRequest = async (requestId: number, response: 'ACEPTAR' | 'RECHAZAR') => {
        try {
            setIsLoading(true);
            await container.respondToContactRequestUseCase.execute(requestId, response);
            await fetchContacts();
            Alert.alert('Éxito', `Solicitud ${response === 'ACEPTAR' ? 'aceptada' : 'rechazada'}.`);
        } catch (err: any) {
            console.error('Error responding:', err);
            Alert.alert('Error', 'No se pudo responder la solicitud.');
        } finally {
            setIsLoading(false);
        }
    };

    const sendContactRequest = async (criteria: string) => {
        try {
            setIsLoading(true);
            const user = await container.getCurrentUserUseCase.execute();
            if (!user) throw new Error('No session');
            await container.sendContactRequestUseCase.execute(String(user.id), criteria);
            return true;
        } catch (err: any) {
            console.error('Error sending request:', err);
            // Handle specific backend errors if needed
            throw err;
        } finally {
            setIsLoading(false);
        }
    };

    const addContact = async (name: string, phone: string, relationship: string, isEmergency: boolean) => {
        try {
            const user = await container.getCurrentUserUseCase.execute();
            if (!user) throw new Error('No session');

            const newContact: Contact = {
                id: '', // Generated by backend
                name,
                phone,
                relationship,
                isEmergency
            };

            await container.addContactUseCase.execute(newContact, String(user.id));
            await fetchContacts();
            return true;
        } catch (err: any) {
            console.error('Error adding contact:', err);
            Alert.alert('Error', 'No se pudo agregar el contacto');
            return false;
        }
    };

    const deleteContact = async (contactId: string) => {
        try {
            await container.deleteContactUseCase.execute(contactId);
            setContacts(prev => prev.filter(c => c.id !== contactId));
        } catch (err: any) {
            console.error('Error deleting contact:', err);
            Alert.alert('Error', 'No se pudo eliminar el contacto');
        }
    };

    const updateContact = async (contactId: string, data: Partial<Contact>) => {
        try {
            setIsLoading(true);
            const existing = contacts.find(c => c.id === contactId);
            if (!existing) throw new Error('Contact not found');
            const updatedContact = { ...existing, ...data };
            await container.updateContactUseCase.execute(updatedContact as Contact);
            await fetchContacts();
            return true;
        } catch (err: any) {
            console.error('Error updating contact:', err);
            Alert.alert('Error', 'No se pudo actualizar el contacto');
            return false;
        } finally {
            setIsLoading(false);
        }
    };

    return {
        contacts,
        requests,
        isLoading,
        error,
        fetchContacts,
        addContact,
        updateContact,
        deleteContact,
        respondToRequest,
        sendContactRequest
    };
};
