import { StyleSheet } from "react-native";
import { normalize } from '../../../shared/utils/dimensions';
import { theme } from '../../styles/theme';

export const styles = StyleSheet.create({

  editIcon: {
    position: "absolute",
    bottom: 10,
    right: 10,
    backgroundColor: "white",
    borderRadius: 15,
    padding: 4,
  },
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    paddingTop: normalize(10), // Menos espacio arriba para subir el formulario
  },
  header: {
    backgroundColor: "transparent", // Transparent to show gradient
    padding: 15,
    alignItems: "center",
  },
  headerText: {
    color: theme.colors.text,
    fontSize: 16,
    fontWeight: "bold",
  },
  profileContainer: {
    alignItems: "center",
    marginTop: 30,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: theme.colors.primary,  // Key visual change
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 4,
  },
  editButton: {
    marginTop: 10,
    backgroundColor: "rgba(0,0,0,0.6)",  // Dark transparent
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 3,
  },
  editButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },
  form: {
    marginTop: 0,
    paddingTop: 30,
    paddingHorizontal: 25,
    paddingBottom: 35, // Menos espacio abajo
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    marginTop: 20,
    color: theme.colors.textSecondary,  // Slightly softer white
  },
  input: {
    backgroundColor: theme.colors.card,  // Glassmorphism
    paddingVertical: 14,
    paddingHorizontal: 15,
    borderRadius: 10,
    marginTop: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
    fontSize: 16,
    color: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 2,
  },
  button: {
    backgroundColor: theme.colors.primary, // Red button
    paddingVertical: 14,
    borderRadius: 10,
    marginTop: 30,
    alignItems: "center",
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 4,
    marginBottom: 30,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  footer: {
    backgroundColor: "#005550", // Check if this is used? Maybe remove later
    padding: 10,
    alignItems: "center",
    position: "absolute",
    bottom: 0,
    width: "100%",
  },
  footerText: {
    color: "#fff",
  },
  footerLink: {
    color: "#FFB400",
    fontWeight: "bold",
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    position: 'absolute',
    right: 10,
  },
  backArrowContainer: {
    position: 'absolute',
    top: normalize(20),
    left: 10,
    zIndex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  phoneLoadingContainer: {
    padding: 20,
    alignItems: 'center',
  },
  phoneLoadingText: {
    color: '#fff',
    marginTop: 8,
    fontSize: 14,
  },
  modalSaveButton: {
    flex: 1,
    marginLeft: 10,
    borderRadius: 8,
    overflow: 'hidden',
  },
  modalSaveButtonGradient: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSaveButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalSaveButtonDisabled: {
    opacity: 0.6,
  },
  modalCancelButton: {
    flex: 1,
    marginRight: 10,
    borderRadius: 8,
    backgroundColor: '#333',
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#555'
  },
  modalCancelButtonText: {
    color: '#aaa',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalButtons: {
    flexDirection: 'row',
    marginTop: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)', // Darker overlay
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: '#1A1A1A', // Dark modal
    borderRadius: 12,
    padding: 20,
    width: '90%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  modalContent: {
    width: '100%',
  },
  errorText: {
    color: '#ff4444',
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    width: '100%',
    paddingHorizontal: 20,
  },
  profileIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  profileTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    flex: 1,
  },
  formContainer: {
    width: '100%',
    paddingHorizontal: 20,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    marginBottom: 15,
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  inputIcon: {
    marginRight: 10,
  },
  inputNew: {
    flex: 1,
    fontSize: 16,
    color: '#fff',
  },
  inputDisabled: {
    opacity: 0.6,
  },
  passwordToggle: {
    padding: 5,
  },
  saveButton: {
    marginTop: 20,
    borderRadius: 12,
    overflow: 'hidden',
  },
  saveButtonGradient: {
    paddingVertical: 15,
    paddingHorizontal: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  phoneSection: {
    width: '100%',
    paddingHorizontal: 20,
    marginTop: 20,
  },
  phoneSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  addPhoneButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 20,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  phoneItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 15,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  phoneItemContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  phoneItemText: {
    marginLeft: 10,
    flex: 1,
  },
  phoneNumber: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
  },
  phoneDetail: {
    fontSize: 14,
    color: '#aaa',
    marginTop: 2,
  },
  emptyPhoneContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyPhoneText: {
    color: '#fff',
    fontSize: 16,
    marginTop: 10,
  },
  emptyPhoneSubtext: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 14,
    marginTop: 5,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 20,
  },

  profileAvatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: theme.colors.primary,
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 4,
  },
  profileAvatarText: {
    fontSize: 44,
    color: '#fff',
    fontWeight: 'bold',
  },
  editButtonStyled: {
    backgroundColor: theme.colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 0,
  },
  phoneSectionContainer: {
    marginTop: 18,
  },
  phoneSectionTitleText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
    marginBottom: 6,
  },
  phoneLoadingView: {
    padding: 20,
    alignItems: 'center',
  },
  phoneLoadingMessage: {
    color: '#fff',
    marginTop: 8,
  },
  phoneItemContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginBottom: 8,
    minHeight: 52,
    justifyContent: 'center',
    width: '100%',
    alignSelf: 'center',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  phoneItemTitleText: {
    color: theme.colors.primary, // Red accents
    fontWeight: 'bold',
    fontSize: 15,
    marginBottom: 2,
  },
  phoneItemNumberText: {
    color: '#eee',
    fontSize: 15,
  },
  noPhoneContainer: {
    padding: 20,
    alignItems: 'center',
  },
  noPhoneText: {
    color: '#fff',
    fontSize: 14,
    opacity: 0.7,
  },
  passwordPlaceholder: {
    color: '#fff',
  },
  saveButtonEdit: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: '50%',
    minWidth: 180,
    maxWidth: 340,
  },
  saveButtonEditDisabled: {
    opacity: 0.6,
  },
  addPhoneSection: {
    alignItems: 'center',
    marginBottom: 24,
    marginTop: 10,
    width: '100%',
  },
  addPhonePrompt: {
    color: '#fff',
    fontSize: 15,
    marginBottom: 8,
  },
  addPhoneBtn: {
    backgroundColor: theme.colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 25,
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 3,
    marginTop: 2,
    alignSelf: 'center',
    minWidth: 180,
    maxWidth: 340,
  },
  addPhoneBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalKeyboardAvoidingView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  modalContentContainer: {
    backgroundColor: '#1E1E1E',
    borderRadius: 18,
    padding: 28,
    width: 320,
    alignItems: 'center',
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 8,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  modalTitleText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.primary,
    marginBottom: 12,
  },
  modalInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  modalInputIcon: {
    marginRight: 8,
    color: theme.colors.textSecondary,
  },
  modalInput: {
    flex: 1,
    fontSize: 16,
    color: '#fff',
    paddingVertical: 10,
  },
  modalInputPlaceholder: {
    color: '#aaa',
  },
  modalSaveBtn: {
    backgroundColor: theme.colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 28,
    borderRadius: 20,
    marginTop: 6,
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  modalSaveBtnIcon: {
    marginRight: 6,
  },
  modalSaveBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalCancelBtn: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalCancelBtnIcon: {
    marginRight: 6,
    color: '#aaa',
  },
  modalCancelBtnText: {
    color: '#aaa',
    fontWeight: 'bold',
    fontSize: 16,
  },
});
