// HomeStyles.ts
import { StyleSheet, Platform, StatusBar } from 'react-native';
import { normalize, screenWidth } from '../../../shared/utils/dimensions';
import { theme } from '../../styles/theme';

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  title: {
    color: theme.colors.text,
    fontSize: normalize(24),
    fontWeight: '400',
    textAlign: 'center',
    marginTop: normalize(30),
    marginBottom: normalize(30),
    textShadowColor: 'rgba(255, 75, 75, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    letterSpacing: 1,
  },
  // Changed "content" to "scrollContent" usage context, or keep name "content" but use flexGrow
  // We will keep "content" name but update properties for ScrollView usage
  content: {
    flexGrow: 1,
    padding: normalize(20),
    alignItems: 'center',
    paddingBottom: normalize(120), // Extra space for bottom tab bar
  },
  buttonContainer: {
    position: 'relative',
    width: normalize(280),
    height: normalize(280),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: normalize(30),
    marginTop: normalize(10),
  },
  linesContainer: {
    position: 'absolute',
    width: normalize(280),
    height: normalize(280),
    top: 0,
    left: 0,
  },
  nearbyPeopleContainer: {
    position: 'absolute',
    width: normalize(300),
    height: normalize(300),
    justifyContent: 'center',
    alignItems: 'center',
  },
  personBubble: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    width: normalize(60),
    height: normalize(80),
  },
  personImage: {
    width: normalize(50),
    height: normalize(50),
    borderRadius: normalize(25),
    borderWidth: 2,
    borderColor: theme.colors.primary,
    backgroundColor: '#000',
    shadowColor: theme.colors.primary,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 8,
  },
  personName: {
    color: theme.colors.text,
    fontSize: normalize(12),
    marginTop: normalize(4),
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  outerButton: {
    width: normalize(200),
    height: normalize(200),
    borderRadius: normalize(300),
    backgroundColor: 'rgba(20, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 10,
    shadowColor: theme.colors.primary,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    transform: [{ scale: 1 }],
    borderWidth: 1,
    borderColor: 'rgba(255, 75, 75, 0.1)',
  },
  outerButtonActive: {
    width: normalize(80),
    height: normalize(80),
    transform: [{ scale: 0.85 }],
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.8,
    shadowRadius: 30,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    borderColor: theme.colors.primary,
  },
  innerButton: {
    width: normalize(160),
    height: normalize(160),
    borderRadius: normalize(200),
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: theme.colors.primary,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.6,
    shadowRadius: 15,
  },
  buttonContent: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    gap: normalize(8),
  },
  subtitleText: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: normalize(14), // Slightly smaller font
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    fontWeight: '500',
  },
  innerButtonActive: {
    width: normalize(70),
    height: normalize(70),
    shadowOpacity: 0.9,
    shadowRadius: 20,
  },
  buttonText: {
    color: 'white',
    fontSize: normalize(60), // Slightly smaller font
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  buttonTextActive: {
    fontSize: normalize(22),
  },
  cancelButton: {
    marginTop: normalize(2),
    padding: normalize(8),
    paddingHorizontal: normalize(16),
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: normalize(15),
    borderWidth: 1,
    borderColor: theme.colors.primary,
  },
  cancelText: {
    color: theme.colors.text,
    fontSize: normalize(14),
    fontWeight: '600',
  },
  emergencyTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(20, 0, 0, 0.8)',
    padding: normalize(10),
    borderRadius: normalize(30),
    marginTop: normalize(20),
    width: screenWidth * 0.45,
    elevation: 5,
    shadowColor: theme.colors.primary,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    gap: normalize(10),
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.primary,
  },
  emergencyText: {
    color: theme.colors.text,
    fontSize: normalize(24),
    fontWeight: 'bold',
    marginLeft: normalize(10),
    textShadowColor: theme.colors.primary,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  countdownText: {
    color: 'white',
    fontSize: normalize(80),
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    marginBottom: normalize(5),
  },
  countdownContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  resolveButton: {
    width: screenWidth * 0.4,
    marginTop: normalize(30),
    elevation: 5,
    shadowColor: theme.colors.success,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    borderRadius: normalize(30),
  },
  resolveGradient: {
    padding: normalize(12),
    borderRadius: normalize(30),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  resolveText: {
    color: '#FFFFFF',
    fontSize: normalize(20),
    fontWeight: '500',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },

  // Botón de seguridad
  securityButton: {
    width: '100%',
    maxWidth: normalize(350),
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: normalize(25),
    padding: normalize(15),
    borderWidth: 1,
    borderColor: theme.colors.primary,
    elevation: 3,
    shadowColor: theme.colors.primary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    alignSelf: 'center',
    marginTop: normalize(30), // Space from elements above
    marginBottom: normalize(20),
  },
  securityButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  securityButtonText: {
    color: theme.colors.text,
    fontSize: normalize(16),
    fontWeight: '600',
    marginLeft: normalize(8),
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },

  // Modal de seguridad
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: normalize(20),
  },
  modalContent: {
    backgroundColor: '#1A1A1A',
    borderRadius: normalize(20),
    width: '100%',
    maxWidth: normalize(350),
    elevation: 20,
    shadowColor: theme.colors.primary,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 75, 75, 0.2)',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: normalize(20),
    paddingBottom: normalize(10),
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  modalTitle: {
    fontSize: normalize(20),
    fontWeight: '600',
    color: theme.colors.text,
    marginLeft: normalize(10),
  },
  modalBody: {
    padding: normalize(20),
  },
  modalDescription: {
    fontSize: normalize(14),
    color: '#AAAAAA',
    marginBottom: normalize(20),
    textAlign: 'center',
  },
  switchContainer: {
    backgroundColor: 'rgba(255, 75, 75, 0.1)',
    borderRadius: normalize(15),
    padding: normalize(15),
    borderWidth: 1,
    borderColor: 'rgba(255, 75, 75, 0.2)',
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: normalize(10),
  },
  switchLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  switchLabel: {
    fontSize: normalize(16),
    fontWeight: '500',
    color: theme.colors.text,
    marginLeft: normalize(10),
  },
  switchDescription: {
    fontSize: normalize(12),
    color: '#888',
    fontStyle: 'italic',
    textAlign: 'center',
  },
  modalFooter: {
    padding: normalize(20),
    paddingTop: normalize(10),
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },
  modalCloseButton: {
    backgroundColor: theme.colors.primary,
    borderRadius: normalize(25),
    padding: normalize(12),
    alignItems: 'center',
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 3,
  },
  modalCloseText: {
    color: '#FFFFFF',
    fontSize: normalize(16),
    fontWeight: '600',
  },
  nearbyValuesButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    paddingVertical: normalize(10),
    paddingHorizontal: normalize(20),
    borderRadius: normalize(20),
    marginTop: normalize(20),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    flexDirection: 'row',
    alignItems: 'center',
  },
  nearbyValuesText: {
    color: theme.colors.text,
    fontSize: normalize(16),
    fontWeight: '500',
  },
});